#!/usr/bin/env python

from __future__ import print_function

from antipathy import Path
from scription import *
from openerplib import get_connection, get_records, MissingRecord

import sys
sys.path.insert(0, '/usr/local/bin/evs')
from hg_tools import extract_hg, find_issues
sys.path.pop(0)

config_file = Path('/etc/openerp/fnx.ini')


@Script()
def main():
    setup()

@Command(
        type=Spec('type of update', choices=['task', 'issue']),
        id=Spec('id of task/issue', type=int),
        status=Spec('new status', choices=['install', 'test']),
        )
def set(type, id, status):
    model = models[type]
    stage = types[stages[status]]
    try:
        get_records(model, ids=id)
    except MissingRecord:
        abort('record not found in %r' % models[type].model_name)
    model.write([id], {'stage_id': stage.id})


@Command()
def update():
    # get primary hg info
    setup()
    hg = extract_hg()
    # get commit desriptions
    job = Execute('hg log -r%s: --template "{desc}\n-=-\n"' % hg.revision)
    if job.returncode or job.stderr:
        if job.stderr:
            error(job.stderr, end='')
        raise SystemExit(job.returncode or 1)
    commits = job.stdout.split('\n-=-\n')[:-1]
    issues = find_issues(*commits)
    for issue in issues:
        set(issue.type, issue.id, 'test')


def ensure_stages(types, type, id, required):
    model = models[type]
    record = get_records(model, ids=id, fields=['id', 'project_id'])
    if record.project_id:
        # some tasks/issues are not assigned to a project
        project_record = get_records(project, ids=record.project_id[0], fields=['type_ids'])
        needs_ids = []
        for req in required:
            type_id = types[req]
            if type_id not in project_record.type_ids:
                needs_ids.append((4, type_id))
        if needs_ids:
            project.write(project_record.id, {'type_ids': needs_ids})


def setup():
    global config, conn, project, project_task, project_issue, project_task_type, models, stages, types
    config = OrmFile(config_file, section='openerp')
    conn = get_connection(hostname=config.host, database=config.db, login=config.user, password=config.pw)
    project = conn.get_model('project.project')
    project_task = conn.get_model('project.task')
    project_issue = conn.get_model('project.issue')
    project_task_type = conn.get_model('project.task.type')
    models = {
            'issue': project_issue,
            'task':  project_task,
            }
    stages = {
            'install': 'Needs installed',
            'test': 'Testing',
            }
    types = dict([
        (r.name, r)
        for r in get_records(project_task_type)
        ])
    if 'Needs installed' not in types:
        new_id = project_task_type.create({
                'name': 'Needs installed',
                'description': 'Code has been created, committed, and pushed to the server. Now needs to be installed on customer machine.',
                'sequence': 5,
                'case_default': True,
                'state': 'open',
                'fold': True,
                })
        types['Needs installed'] = new_id
    if 'Testing' not in types:
        new_id = project_task_type.create({
                'name': 'Testing',
                'description': 'With this method of completing the task, does it work?',
                'sequence': 6,
                'case_default': True,
                'state': 'open',
                'fold': False,
                })
        types['Testing'] = new_id

Main()
