#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

from scription import *
import openerp
import openerp.osv
from openerp.osv.orm import browse_null as BrowseNull
from openerp.osv.osv import except_osv as ERPError
from openerp.tools import config
from openerp.tests import common
from openerp.addons.fnx import Date, Time, DateTime
import time
from unittest2 import main as Test, skip

@Script(
        conf=Spec('configuration file to use', OPTION, remove=True, default='/etc/openerp/server.conf'),
        tests=Spec('tests to run', OPTION),
        )
def main(conf, *tests):
    config.parse_config(['--conf', conf])
    # inject the configure values back in to openerp.common
    common.ADDONS_PATH = config['addons_path']
    common.PORT = config['xmlrpc_port']
    common.DB = config['db_name']
    common.HOST = '127.0.0.1'
    common.ADMIN_USER = 'admin'
    common.ADMIN_USER_ID = openerp.SUPERUSER_ID
    common.ADMIN_PASSWORD = config['admin_passwd']


@Command(
        calendar=Spec('which calendar to test', choices=['base','crm'], remove=True),
        )
def test_calendar(calendar):
    # print('main usage', main.__usage__, verbose=0)
    # print('test_calendar usage', test_base_calendar.__usage__, verbose=0)
    # raise Exception
    if calendar == 'base':
        TestCalendar.calendar = 'calendar.event'
    elif calendar == 'crm':
        TestCalendar.calendar = 'crm.meeting'
    else:
        raise Exception('oops')
    Test()


class TestCalendar(common.TransactionCase):

    calendar = None

    def setUp(self):
        """*****setUp*****"""
        print('\n--== setting up ==--', verbose=2)
        super(TestCalendar, self).setUp()
        cr, uid, registry = self.cr, self.uid, self.registry
        context = {}
        res_partner = registry('res.partner')
        res_users = registry('res.users')
        res_groups = registry('res.groups')
        res_alarm = registry('res.alarm')
        mail_group = registry('mail.group')
        ir_model_data = registry('ir.model.data')
        mail_message = registry('mail.message')
        calendar_event = registry(self.calendar)
        calendar_attendee = registry('calendar.attendee')
        lunch_time = DateTime.combine(Date.today(), Time(21)).strftime("%Y-%m-%d %H:%M:%S") # noonish PST
        alarm5_id = res_alarm.browse(cr, uid, [('name','=','5 minutes before')], context)[0].id
        alarm15_id = res_alarm.browse(cr, uid, [('name','=','15 minutes before')], context)[0].id
        vals = res_users._add_missing_default_values(cr ,uid, {'login':'calendar_user1', 'name':'Calendar User I'})
        test_uid1 = res_users.create(cr, uid, vals)
        test_pid1 = res_users.browse(cr, uid, test_uid1, context).partner_id.id
        print('user1 -> uid: %s  pid: %s' % (test_uid1, test_pid1))
        vals.update(login='calendar_user2', name='Calendar User II')
        test_uid2 = res_users.create(cr, uid, vals)
        test_pid2 = res_users.browse(cr, uid, test_uid2, context).partner_id.id
        print('user2 -> uid: %s  pid: %s' % (test_uid2, test_pid2))
        vals.update(login='calendar_user3', name='Calendar User III')
        test_uid3 = res_users.create(cr, uid, vals)
        test_pid3 = res_users.browse(cr, uid, test_uid3, context).partner_id.id
        print('user3 -> uid: %s  pid: %s' % (test_uid3, test_pid3))
        vals = mail_group._add_missing_default_values(cr ,uid, {'name':'Test Gurus', 'description':'just a test group'})
        test_mgid1 = mail_group.create(cr, uid, vals)
        test_mguid1 = mail_group.browse(cr, uid, test_mgid1, context).user_proxy_id.id
        print('mailgroup1 -> id: %s  uid: %s' % (test_mgid1, test_mguid1))
        vals.update(name='Test Sellers', description='Another test group')
        test_mgid2 = mail_group.create(cr, uid, vals)
        test_mguid2 = mail_group.browse(cr, uid, test_mgid2, context).user_proxy_id.id
        print('mailgroup2 -> id: %s  uid: %s' % (test_mgid2, test_mguid2))
        del vals
        # inject locals into self
        for k, v in locals().items():
            setattr(self, k, v)

    def tearDown(self):
        print('--== tearing down ==--\n', verbose=2)
        super(TestCalendar, self).tearDown()

    def _create(self, model, cr, uid, values, context=None):
        values = model._add_missing_default_values(cr, uid, values)
        return model.create(cr, uid, values, context)

    def _compare_events(self, event, *copies):
        for copy in copies:
            for field in self.calendar_event._columns.keys():
                if field in ('user_id', 'alarm_id', 'base_calendar_alarm_id', 'master_event_id', 'id') or field.startswith('message_'):
                    continue
                if isinstance(event[field], BrowseNull) and isinstance(copy[field], BrowseNull):
                    continue
                self.assertEqual(event[field], copy[field], 'field %r is not the same' % field)

    def test_simple_create(self, partner_ids=None, alarm_id=None):
        """creating user should end up in partner_ids (Attendees)"""
        cr, uid, context = self.cr, self.uid, self.context
        vals = dict(
                name='Lunch Break',
                description='Time for some yummy hot food',
                date=self.lunch_time,
                )
        vals['partner_ids'] = [(6, False, partner_ids or [])]
        if vals['partner_ids'][0][2]:
            vals['is_individual_invite'] = True
        if alarm_id is not None:
            vals['alarm_id'] = alarm_id
        vals.update(self.calendar_event.onchange_dates(cr, uid, None, vals['date'], context=context)['value'])
        event_id = self._create(self.calendar_event, cr, self.test_uid1, vals, context=context)
        event = self.calendar_event.browse(cr, uid, event_id, context)
        self.assertEqual(event.user_id.id, self.test_uid1)
        self.assertEqual(event.date, self.lunch_time)
        self.assertEqual(len(event.partner_ids), 1+(len(partner_ids or []) or -1))
        if vals['partner_ids'][0][2]:
            self.assertIn(self.test_pid1, [p.id for p in event.partner_ids])
        return event

    def test_simple_create_for_mail_group(self, partner_ids=None, alarm_id=None, extra_mail_group_ids=None):
        """creating user should not end up in partner_ids (Attendees), responsible_id should be mail group"""
        cr, uid, context = self.cr, self.uid, self.context
        mail_group_ids = [self.test_mgid1] + (extra_mail_group_ids or [])
        vals = dict(
                name='Lunch Meeting',
                description='Time for some yummy hot food and technical discussion',
                date=self.lunch_time,
                mail_group_ids=[(6, False, mail_group_ids)],
                partner_ids=[(6, False, partner_ids or [])],
                )
        if vals['partner_ids'][0][2]:
            vals['is_individual_invite'] = True
        if alarm_id is not None:
            vals['alarm_id'] = alarm_id
        vals.update(self.calendar_event.onchange_dates(cr, uid, None, vals['date'], context=context)['value'])
        event_id = self._create(self.calendar_event, cr, self.test_uid1, vals, context=context)
        event = self.calendar_event.browse(cr, uid, event_id, context)
        self.assertEqual(event.user_id.id, self.test_uid1)
        self.assertEqual(event.date, self.lunch_time)
        self.assertEqual(len(event.partner_ids), len(partner_ids or []))
        self.assertNotIn(self.test_pid1, [p.id for p in event.partner_ids])
        self.assertIn(self.test_mgid1, [e.id for e in event.mail_group_ids])
        for extra_mgid in mail_group_ids[1:]:
            self.assertIn(extra_mgid, [e.id for e in event.mail_group_ids])
        slave_events = self.calendar_event.browse(cr, uid, [('master_event_id','=',event_id)], context)
        self.assertEqual(len(mail_group_ids), len(slave_events))
        return event

    def test_single_invite_create(self, alarm_id=None):
        cr, uid, context = self.cr, self.uid, self.context
        event = self.test_simple_create(partner_ids=[self.test_pid2], alarm_id=alarm_id)
        partner_ids = [p.id for p in event.partner_ids]
        self.assertIn(self.test_pid1, partner_ids)
        self.assertIn(self.test_pid2, partner_ids)
        return event

    def test_slave_events_created_with_master_event(self):
        "extra partners specified at initial creation should trigger slave events at the same time"
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2copies = self.calendar_event.browse(cr, uid, [('master_event_id','=',event2.id)], context)
        self.assertEqual(len(event2copies), 1)
        self.assertEqual(event2copies[0].user_id.id, self.test_uid2)
        for copy in event2copies:
            self.assertEqual(event2['organizer'], copy['organizer'])

    def test_unallowed_changes_on_master_event(self):
        "changing name, description, location, tags, attendees, etc, not allowed unless user is master event owner"
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        for k, v in (
                ('name', 'Lunch intermission'),
                ('description', 'a midday break'),
                ('location', 'whereever'),
                ('organizer', 'you, yourself, and... you?'),
                ('date', DateTime.now()),
                ('duration', 2.5),
                ('user_id', self.test_uid2),
                ('partner_ids', ([6, False, []])),
                ('alarm_id', self.alarm15_id),
                ('show_as', 'free'),
                ):
            self.assertRaises(ERPError, self.calendar_event.write, cr, self.test_uid2, [event2.id], {k: v}, context)

    def test_unallowed_changes_on_slave_event(self):
        "changing name, description, location, tags, attendees, etc, not allowed on event slaves unless user is master event owner"
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2copy = self.calendar_event.browse(cr, uid, [('master_event_id','=',event2.id)], context)[0]
        for k, v in (
                ('name', 'Lunch intermission'),
                ('description', 'a midday break'),
                ('location', 'whereever'),
                ('organizer', 'you, yourself, and... you?'),
                ('date', DateTime.now()),
                ('duration', 2.5),
                ('user_id', self.test_uid2),
                ('partner_ids', ([6, False, []])),
                ):
            self.assertRaises(ERPError, self.calendar_event.write, cr, self.test_uid2, [event2copy.id], {k: v}, context)

    def test_allowed_changes_on_slave_event_by_master_event_owner(self):
        "changing name, description, location, tags, attendees, etc, not allowed on event slaves unless user is master event owner"
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2copy = self.calendar_event.browse(cr, uid, [('master_event_id','=',event2.id)], context)[0]
        for k, v in (
                ('name', 'Lunch intermission'),
                ('description', 'a midday break'),
                ('location', 'whereever'),
                ('duration', 2.5),
                ):
            self.assertTrue(self.calendar_event.write(cr, self.test_uid1, [event2copy.id], {k: v}, context))
            event2.refresh()
            event2copy.refresh()
            self.assertTrue(event2[k] == event2copy[k] == v)

    def test_allowed_changes_on_slave_event(self):
        "changing alarm and show-as is allowed on event slaves"
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2copy = self.calendar_event.browse(cr, uid, [('master_event_id','=',event2.id)], context)[0]
        for k, v in (
                ('alarm_id', self.alarm5_id),
                ('show_as', 'free'),
                ):
            self.calendar_event.write(cr, self.test_uid2, [event2copy.id], {k: v}, context)

    def test_master_and_slave_events_share_attendees(self):
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2copy = self.calendar_event.browse(cr, uid, [('master_event_id','=',event2.id)], context)[0]
        master_event_attendees = set([att.id for att in event2.attendee_ids])
        slave_event_attendees = set([att.id for att in event2copy.attendee_ids])
        self.assertEqual(master_event_attendees, slave_event_attendees)

    def test_slave_events_have_same_data(self):
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2copy = self.calendar_event.browse(cr, uid, [('master_event_id','=',event2.id)], context)[0]
        self._compare_events(event2, event2copy)

    def test_slave_events_have_same_updated_data(self):
        "make sure changes to master event are reflected in slaves"
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2.write({'name':'New and Improved!'})
        event2.refresh()
        self.assertEqual(event2.name, 'New and Improved!')
        event2copy = self.calendar_event.browse(cr, uid, [('master_event_id','=',event2.id)], context)[0]
        self._compare_events(event2, event2copy)

    def test_adding_new_partners_creates_new_slaves(self):
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2copies1 = self.calendar_event.browse(cr, uid, [('master_event_id','=',event2.id)], context)
        event2.write({'partner_ids':[(4, self.test_pid3)]})
        event2copies2 = self.calendar_event.browse(cr, uid, [('master_event_id','=',event2.id)], context)
        self.assertEqual(len(event2copies1) + 1, len(event2copies2))

    def test_slave_events_share_new_attendees(self):
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2.write({'partner_ids':[(4, self.test_pid3)]})
        event2.refresh()
        event2copies = self.calendar_event.browse(cr, uid, [('master_event_id','=',event2.id)], context)
        self._compare_events(event2, *event2copies)

    def test_slave_events_do_not_share_alarms(self):
        cr, uid, context = self.cr, self.uid, self.context
        event3 = self.test_simple_create(
                partner_ids=[self.test_pid2, self.test_pid3],
                alarm_id=self.alarm5_id,
                )
        self.assertEqual(event3.alarm_id.id, self.alarm5_id)
        slave1, slave2 = self.calendar_event.browse(cr, uid, [('master_event_id','=',event3.id)], context)
        self.assertEqual(slave1.alarm_id.id, self.alarm5_id)
        self.assertEqual(slave2.alarm_id.id, self.alarm5_id)
        slave1.write({'alarm_id':False})
        slave2.write({'alarm_id':self.alarm15_id})
        event3.refresh()
        slave1.refresh()
        slave2.refresh()
        self.assertEqual(event3.alarm_id.id, self.alarm5_id)
        self.assertFalse(slave1.alarm_id)
        self.assertEqual(slave2.alarm_id.id, self.alarm15_id)


    def test_delete_master_event_deletes_all_events_and_attendees(self):
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2_id = event2.id
        attendee_ids = [att.id for att in event2.attendee_ids]
        self.assertEqual(len(attendee_ids), 2)
        self.calendar_event.unlink(cr, self.test_uid1, [event2.id], context)
        event2copy_ids = self.calendar_event.search(
                cr,
                uid,
                ['|',('master_event_id','=',event2_id),('id','=',event2_id)],
                context,
                )
        self.assertEqual(len(event2copy_ids), 0)
        current_attendee_ids = self.calendar_attendee.search(cr, uid, [('id','in',attendee_ids)], context=context)
        self.assertEqual(len(current_attendee_ids), 0)

    def test_delete_slave_event_declines_invite(self):
        cr, uid, context = self.cr, self.uid, self.context
        event2 = self.test_single_invite_create()
        event2copy_ids = self.calendar_event.search(cr, uid, [('master_event_id','=',event2.id)], context)
        self.assertTrue(len(event2copy_ids) == 1)
        self.calendar_event.unlink(cr, self.test_uid2, event2copy_ids, context)
        event2copy_ids = self.calendar_event.search(cr, uid, [('master_event_id','=',event2.id)], context)
        self.assertTrue(len(event2copy_ids) == 0)
        test2_attendee = [att for att in event2.attendee_ids if att.user_id.id == self.test_uid2][0]
        self.assertEqual(test2_attendee.state, 'declined')


Main()
