#!/usr/local/sbin/suid-python --virtualenv
from __future__ import print_function

from scription import *
from openerplib import get_connection, AttrDict
import os
import socket

CONFIG = OrmFile('%s/config/fnx.ini' % os.environ['VIRTUAL_ENV'], section='openerp')

def connect():
    OE = AttrDict()
    OE.conn = get_connection(hostname=CONFIG.host, database=CONFIG.db, login=CONFIG.user, password=CONFIG.pw)
    return OE

@Command()
def check_openerp():
    "simple heart-beat test by attempting to connect to OpenERP"
    try:
        print('connecting...', end=' ')
        connect()
        print('success!')
    except socket.error as exc:
        if exc.errno == 111:
            print('OpenERP is not running, restarting')
            with user_ids(0, 0):
                os.system('/etc/init.d/openerp start')
        else:
            raise

Main()
