#!/usr/local/sbin/suid-python --virtualenv
from __future__ import print_function

from scription import *
from openerplib import get_connection, AttrDict
import os

CONFIG = OrmFile('%s/config/fnx.ini' % os.environ['VIRTUAL_ENV'], section='openerp')

def connect():
    OE = AttrDict()
    OE.conn = get_connection(hostname=CONFIG.host, database=CONFIG.db, login=CONFIG.user, password=CONFIG.pw)
    return OE

@Command()
def check_openerp():
    "simple heart-beat test by attempting to connect to OpenERP"
    hopeful = wait_and_check(300, 15)
    while True:
        try:
            print('connecting...', end=' ')
            connect()
            print('success!')
            break
        except Exception:
            if not hopeful:
                raise

Main()
