#!/usr/local/sbin/suid-python --virtualenv
"""
Checks if OpenERP is still running.

If not, kill all processes attempting to communicate with OpenERP (except this
one), then restart OpenERP.

Test 1: check that heartbeat file is less than three minutes old.
Test 2: check that a connection takes less than 60 seconds.

Issue an alert after each failed test.

TODO:
> examine system during a failure to see what information is available as
> to which processes to kill.

Issue an all-clear once OpenERP is up and running again.
"""
from __future__ import print_function

from scription import *
from antipathy import Path
from datetime import timedelta
from fnx_script_support import Notify
from openerplib import get_connection, AttrDict
import os
import socket
import time

CONFIG = OrmFile('%s/config/fnx.ini' % os.environ['VIRTUAL_ENV'], section='openerp')
CRON_BEAT = Path('/home/openerp/sandbox/openerp/var/cron_updates')
CUT_OFF = timedelta(seconds=7*60+30)


def connect():
    OE = AttrDict()
    OE.conn = get_connection(hostname=CONFIG.host, database=CONFIG.db, login=CONFIG.user, password=CONFIG.pw)
    return OE

@Command()
def server():
    """
    simple heart-beat test by attempting to connect to OpenERP
    """
    now = time.time()
    restart_at = now + 7 * 60
    print('connecting...', end=' ')
    first_time = True
    while 'waiting for signs of life':
        try:
            connect()
            print('success!')
            break
        except socket.error as exc:
            if exc.errno == 111:
                if first_time:
                    print('\n  OpenERP is not running...')
                    first_time = False
                else:
                    print()
                if time.time() < restart_at:
                    print('    waiting a bit...', end=' ')
                    time.sleep(60)
                    continue
                else:
                    print('\n    restarting.')
                    with user_ids(0, 0):
                        os.system('/etc/init.d/openerp start')
                    break
            else:
                # unknown error
                raise

@Command()
def cron_update():
    """
    update CRON_BEAT file with current time stamp; should be run from OE's scheduler
    """
    CRON_BEAT.touch()


@Command()
def cron():
    """
    Determine if the OE scheduler is still running.
    """
    errors = []
    if not CRON_BEAT.exists():
        errors.append('OpenERP cron heartbeat file %s is missing')
    else:
        last_update = DateTime.fromtimestamp(CRON_BEAT.stat().st_mtime)
        if DateTime.now() - last_update > CUT_OFF:
            errors.append('OpenERP scheduler is no longer functioning; please restart OpenERP')
    notify = Notify('check_openerp_cron')
    notify(errors)


Main()
